version: '3.8'

# visite o canal GS Tech - https://www.youtube.com/@GS-Tech27

services:  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: <SEU_EMAIL>
      PGADMIN_DEFAULT_PASSWORD: <SUA_SENHA>
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      resources:
          limits:
            cpus: '0.4'
            memory: 256M
    networks:
        - npm_public
        - app_network

networks:
  npm_public:
    external: true
  app_network:
    external: true

volumes:
  pgadmin_data:
    external: true