version: "3.8"

# visite o canal GS Tech - https://www.youtube.com/@GS-Tech27

services:
  postgres:
    image: postgres:15
    command: [postgres, --max_connections=100]
    environment:
      - POSTGRES_PASSWORD=SUA_SENHA_AQUI
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  postgres_data:
    external: true

networks:
  app_network:
    external: true