version: "3.8"

# visite o canal GS Tech - https://www.youtube.com/@GS-Tech27

services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    # caso queira utilizar com senha, utilize essa linha abaixo.
    #command: ["redis-server", "--appendonly", "yes", "--port", "6379", "--requirepass", "SENHA_AQUI"]
    networks:
      - app_network
    volumes:
      - redis_data:/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      placement:
        constraints:
          - node.role == manager

volumes:
  redis_data:
    external: true

networks:
  app_network:
    external: true