version: "3.8"

# visite o canal GS Tech - https://www.youtube.com/@GS-Tech27

services:
  typebot_builder:
    image: baptistearno/typebot-builder:latest
    networks:
      - npm_public
      - app_network
    environment:
      #user:pass@hostname:porta/banco
      DATABASE_URL: postgresql://postgres:<SENHA>@postgres:5432/typebot
      ENCRYPTION_SECRET: <SUA_CHAVE_SECRETA>
      NEXTAUTH_URL: https://builder.SEU_DOMINIO.com.br
      NEXT_PUBLIC_VIEWER_URL: https://typechat.SEU_DOMINIO.com.br
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      ADMIN_EMAIL: <SEU_EMAIL_PARA_CONTA_ILIMITADA>
      #defina como "true" para desabilitar novos cadastros, faça isso depois de fazer o primeiro login
      DISABLE_SIGNUP: "false"
      #SMTP
      SMTP_HOST: smtp.gmail.com
      SMTP_USERNAME: <EMAIL_DO_SMTP>
      SMTP_PASSWORD: <SENHA_AQUI>
      #coloque dentro do sinal de maior e menor ex: <@email.com.br>
      #Infomome o mesmo valor utilizado da variavel SMTP_USERNAME
      NEXT_PUBLIC_SMTP_FROM: "GS Tech <SEU_EMAIL@email.com>"
      SMTP_PORT: 465
      SMTP_SECURE: "true"
      #Minio
      S3_ACCESS_KEY: <USUARIO_MINIO>
      S3_SECRET_KEY: <SENHA_MINIO>
      S3_BUCKET: typebot
      S3_ENDPOINT: s3.SEU_DOMINIO.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      

  typebot_viewer:
    image: baptistearno/typebot-viewer:latest
    networks:
      - npm_public
      - app_network
    environment:
      DATABASE_URL: postgresql://postgres:<SENHA>@postgres:5432/typebot
      ENCRYPTION_SECRET: <SUA_CHAVE_SECRETA>
      NEXTAUTH_URL: https://builder.SEU_DOMINIO.com.br
      NEXT_PUBLIC_VIEWER_URL: https://typechat.SEU_DOMINIO.com.br
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      ADMIN_EMAIL: <SEU_EMAIL_PARA_CONTA_ILIMITADA>
      #defina como "true" para desabilitar novos cadastros, faça isso depois de fazer o primeiro login
      DISABLE_SIGNUP: "false"
      #SMTP
      SMTP_HOST: smtp.gmail.com
      SMTP_USERNAME: <EMAIL_DO_SMTP>
      SMTP_PASSWORD: <SENHA_AQUI>
      #coloque dentro do sinal de maior e menor ex: <@email.com.br>
      #Infomome o mesmo valor utilizado da variavel SMTP_USERNAME
      NEXT_PUBLIC_SMTP_FROM: "GS Tech <SEU_EMAIL@email.com>"
      SMTP_PORT: 465
      SMTP_SECURE: "true"
      #Minio
      S3_ACCESS_KEY: <USUARIO_MINIO>
      S3_SECRET_KEY: <SENHA_MINIO>
      S3_BUCKET: typebot
      S3_ENDPOINT: s3.SEU_DOMINIO.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      
networks:
  npm_public:
    external: true
  app_network:
    external: true